# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ._.
description: Tooster's playground
author:
  discord: Tooster#3471
  github_username:  T3sT3ro
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://T3sT3ro.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# remote_theme: T3sT3ro/T3sT3ro.github.io@theme

markdown: kramdown
sass:
  style: compact
  sourcemap: development
kramdown:
  input: GFM
  gfm_emojis: true
  math_engine: mathjax
  syntax_highlighter:
  syntax_highlighter_opts: 
    disable: true

    
defaults:
  - scope:
      path: ""
    values:
      layout: post


# TODO: add comments to posts via giscuis https://www.freecodecamp.org/news/github-discussions-as-chat-system/
  
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-relative-links

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - frontmatter.json
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
  - docker-compose.yml