services:
  jekyll-server:
    image: jekyll/jekyll:4.2.2
    volumes:
      - .:/srv/jekyll:Z
      - ./vendor/bundle:/usr/local/bundle:Z
    ports:
      - '[::1]:4000:4000'
      - '[::1]:35729:35729'
    command: jekyll serve --drafts
